export interface IUser {
  name: string,
  surname: string,
  email: string,
  profileImageUrl: string,
  backgroundImageUrl: string,
  tNumber: string,
  biography: string,
  followersAmount: number
  // id: string,
  // name: string,
  // surname: string,
  // password: string,
  // email: string,
  // biography: string,
  // tNumber: number,
  // subscribed: number,
  // subdomain: string,
  // image: string,
  // followers: number,
}
